modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "logo.png" #optional
credits = "Thanks for stohun for the amazing models" #optional
authors = "${mod_author}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory
versionRange = "${neoforge_loader_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "soulfired"
type="optional"
versionRange = "[3.2.1.0,)"
ordering = "NONE"
side = "BOTH"

[mc-publish]
loaders = ['neoforge']
dependencies = [
    "soulfired@3.2.1.0(optional){modrinth:d6MhxwRo}{curseforge:662413}"
]